### ISSUE TITLE
User level can be changed by admins only

### ISSUE THREAD

**Issue by Mitiko** [Azer0s/Olymp#15]
**Is your feature request related to a problem? Please describe.**
Easy elevation of privileges. User level should be changed only by admins.

**Describe the solution you'd like**
Admins only can change user level.

**Describe alternatives you've considered**
Being hacked.

**Additional context**
The "level" property of the user is not descriptive enough. Please change to something like AuthLevel

**Comment by alexmandt** [comment]
I could do that.

**Comment by Mitiko** [comment]
We'd love a pull request!

**Comment by alexmandt** [comment]
So. I've tried to get into the configuration tool, but always receive the following error. (with the code from the dev branch)

![grafik](https://user-images.githubusercontent.com/9798095/61252104-b9f23980-a75c-11e9-87f7-429f66ec53e5.png)

I also tried getting into the configuration tool with the code from the master branch, and there it works, (although with a different command):
![grafik](https://user-images.githubusercontent.com/9798095/61252201-10f80e80-a75d-11e9-932a-73b3a265b3c1.png)

I traced the point where the StackOverflowException occurs back to this method call:
![grafik](https://user-images.githubusercontent.com/9798095/61252265-4270da00-a75d-11e9-9c29-d8921af8ca72.png)

So, has anyone else had this problem, or am I the first one to find out about that?

**Comment by alexmandt** [comment]
PS: Should I create an issue for that?

**Comment by Mitiko** [comment]
Definitely create an issue! I'm checking it out as I type this

**Comment by alexmandt** [comment]
So, there are two ways that I could make the system honor the permission level:
1. Make the client send something that proves that he/she has the permission level to do something (would need to modify the Message format
2. Build an Authorization System into the Configuration Server that tracks who logs in and their permission level. 

The first choice would be quick, but not extendable (it would be necessary to add some kind of permission proof to every message that would need some permission-based security)
So I would go with the second choice. I would have to build an authorization system. The question is: 
Do we wanna make a home-grown solution or use something like [Casbin](https://github.com/casbin/Casbin.NET)? 

I guess I'll just start with the home-grown solution and when the time comes, migrating to something more feature-rich should be doable if necessary.
