### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by Azer0s** [Azer0s/Olymp#2]

**Comment by Mitiko** [comment]
Do you prefer to have logging as a static class. If so, what about changing the invocations to `Log.Error` or `Log.Info`

**Comment by Azer0s** [comment]
@Mitiko Log should def. stay static

**Comment by Mitiko** [comment]
TODO:
- [ ] Add ToUser extension to AddUserMessage
- [ ] Refactor Olymp.Nodes
- [ ] Refactor Olymp.Communication 's servers

**Comment by Azer0s** [comment]
- [ ] Use disposable in `Encrypt `and `Decrypt`

**Comment by Mitiko** [comment]
I also have to change the path of MessagePack nuget package, currently it points to a local dll

**Comment by Azer0s** [comment]
Oh damn

**Comment by Azer0s** [comment]
Wait...actually this is fine

**Comment by Mitiko** [comment]
I'm on Linux, so no

**Comment by Mitiko** [comment]
> * [ ]  Use disposable in `Encrypt` and `Decrypt`

What do you mean by use disposable?  Like make the `RijndaelManager` disposable?

**Comment by Mitiko** [comment]
So we're done here?
