### ISSUE TITLE
StackOverflowException when trying to connect to Master Node with Configuration CLI

### ISSUE THREAD

**Issue by alexmandt** [Azer0s/Olymp#33]
**Working branch**
dev

**Describe the bug**
When starting Olymp with the "--configure" flag and trying to connect to a master node, a 
StackOverflowException is thrown

**To Reproduce**
1. Start a Master Node (./olymp --master --name master.local --webui)
2. Connect to local Master Node with Configuration CLI (./olymp --configure localhost --user admin --password admin)
3. Get Error

**Expected behavior**
The Configuration CLI should appear, ready to receive commands.

**Screenshots**
Error with Command:
![grafik](https://user-images.githubusercontent.com/9798095/61253488-7fd76680-a761-11e9-8b63-89af68cb4a2d.png)

Expected Behaviour:
![grafik](https://user-images.githubusercontent.com/9798095/61253505-8b2a9200-a761-11e9-9e40-db220af4f97c.png)

**Desktop (please complete the following information):**
 - OS1: Windows 10 Insider Build 18932 (.NET Core 2.2)
 - OS2: Pop_OS 18.04 LTS (.NET Core 2.2)

**Additional context**
I was working on #15 when I tried to see if I could use the Configuration CLI, so that I could later test if my work actually worked. Discovered the behaviour during the initial try to connect.

After some rudimentiary debugging, I found out that the error is thrown after this method is called: 
![grafik](https://user-images.githubusercontent.com/9798095/61253692-1c9a0400-a762-11e9-80d9-989d25531f89.png)

**Comment by Mitiko** [comment]
Seems like we assume `server` is an ip when we create the TCP stream to connect to the node. Can you try with passing 127.0.0.1:9999 instead of localhost. Try it out with different ports as well, but I believe any should work

**Comment by alexmandt** [comment]
So. I tried to use the following addesses to connect the CLI with my local master node:
-> 127.0.0.1:9999
-> (My local network ip) 192.168.119.137:17929 

I also had to comment a Validation line, so that I could use these adresses.
Or else, I would get this error:
![grafik](https://user-images.githubusercontent.com/9798095/61271867-0150e800-a7a6-11e9-8880-d36645a7d80f.png)

Still. I got the StackOverflowException again. So that didn't help.
Sadly.

**Comment by Mitiko** [comment]
The Uri.ChackHostname thinks 127.0.0.1:9999 isn't IPv4 because of the port, obviously... :disappointed:  
I tried with 127.0.0.1 only, and it still throws a StackOverflow 
When debugging the exception pops up just after we call `NodeCommunicationClient.Send()`, yet I couldn't step into the method.  

I think this might be from one of the other 2 threads. @Azer0s any ideas?

**Comment by Azer0s** [comment]
@Mitiko @alexmandt Currently checking this out. I'm pretty sure it's a parsing bug.

**Comment by Mitiko** [comment]
No, set default ports.  
BTW, the other two threads come from the Program.Title, but don't have effect on the main thread

**Comment by Azer0s** [comment]
Okay I checked the parsing. It's definitely not a parsing error.

**Comment by Azer0s** [comment]
Okay. I know what the error is.

**Comment by Azer0s** [comment]
Something must have went wrong when you exported the messages to Nuget

![image](https://user-images.githubusercontent.com/16290284/61276184-d10e4700-a7af-11e9-9ab5-308bc6a74223.png)

**Comment by Azer0s** [comment]
@Mitiko Can I close the issue here and you just open one in the messages repo?

**Comment by Mitiko** [comment]
@Azer0s yeah, sure, I'm just wondering why that happened  
That's the original:
```
[MessagePackObject(true)]
    public class SingleValueMessage : IMessage
    {
        public string Value
        {
            get => Value;
            set
            {
                if (Validator.ValidateStringValues(value))
                    Value = value;
            }
        }
    }
```

I just replaced Validator.ValidateStringValues with the content in it to remove dependencies:

```
[MessagePackObject(true)]
    public class SingleValueMessage : IMessage
    {
        public string Value
        {
            get => Value;
            set
            {
                if (string.IsNullOrEmpty(value))
                    throw new ArgumentException(value);
                else
                    Value = value;
            }
        }
    }
```

**Comment by Azer0s** [comment]
@Mitiko You need a `private string _value` for this to work.

**Comment by Azer0s** [comment]
Value = value references to itself, calling set on Value

**Comment by Azer0s** [comment]
It appears that, yes, it was flawed from the beginning

**Comment by Mitiko** [comment]
We'll have to wait a bit for the package to get listed and I'll update the references
