### ISSUE TITLE
NodeCommunicationClient can't parse IPs, because ports can't go through the Validator

### ISSUE THREAD

**Issue by Mitiko** [Azer0s/Olymp#36]
**Describe the bug**
In order for NodeCommunicationClient to parse the ip from ConfigurationTool it needs to have an ip. If the passed address (from args) is localhost, the Validator (Uri.CheckHostName specifically) counts it as dns, but if it's 127.0.0.1 as IPv4. If we now pass a port (localhost:1234 or 127.0.0.1:1234), both become Unknown and an InvalidIpOrHostnameException is thrown.
If we don't pass the port, NodeCommunicationClient tries to parse it if there were a port (splits it by ':' and the port is the second element in the array) and that throws IndexOutOfRangeException

**To Reproduce**
You don't even have to start the master node  
1. dotnet run --project Olymp/Olymp.csproj --conf localhost -u admin -p admin

**Expected behavior**
The Configuration tool would start listening on the adress, instead of throwing

**Screenshots**
![Screenshot from 2019-07-16 11-59-29](https://user-images.githubusercontent.com/26521741/61280806-37e82c00-a7c1-11e9-9142-df5091645ab8.png)
![Screenshot from 2019-07-16 11-59-16](https://user-images.githubusercontent.com/26521741/61280807-3880c280-a7c1-11e9-8e29-7ea3f35e4532.png)

**Desktop (please complete the following information):**
 - OS: Linux x64
 - Dotnet version: 2.2.300

**Additional context**
I'm too lazy to file another bug report, but that shouldn't be happening:
![Screenshot from 2019-07-16 11-58-56](https://user-images.githubusercontent.com/26521741/61280808-3880c280-a7c1-11e9-850c-771b5d2ad7e5.png)

**Possible fixes**
We can either:
1. Allow ports in Validator.ValidateAddress
2. Set default port in ConfigurationTool constructor
3. Set default port in NodeCommunicationClient

**Comment by Azer0s** [comment]
@Mitiko Working on it!

**Comment by Mitiko** [comment]
There's not much to be done here, we have to decide where to allow the ports to come in (validator, confTool, or the server). Let me know if you can reproduce

**Comment by alexmandt** [comment]
I can reproduce it. Have the issue while I am working on my own issue.

**Comment by Mitiko** [comment]
My PR is almost ready, but I found more bugs while at it:  
We don't check properly with the Validator at ConfigureManager lines 33, 39, 44
In configuration the MasterIp looks like #33 
We trust the ip provided has been validated by the ConfigurationManager
