### ISSUE TITLE
Use a more reliable hashing algorithm

### ISSUE THREAD

**Issue by Mitiko** [Azer0s/Olymp#6]
MD5 is too short and not the safest. Worse with no salting.
My implementation uses guids for salting:
https://github.com/Mitiko/125School-Website/blob/dev/SchoolWebsite.Application/CryptoService.cs#L19-L34

According to this [website](https://crackstation.net/hashing-security.htm#properhashing) RNGCryptoServiceProvider is more reliable, but I feel it's rather kinda sloppy.

**Comment by Azer0s** [comment]
No. The point is that it's fast. It's doesn't need to be *extremely* secure as we will do a session key encryption anyway and the key is exchanged once. Everything else but md5 will be too slow.

**Comment by Mitiko** [comment]
At least add salting?

**Comment by Mitiko** [comment]
Plus if the NodeComunicationClient (which is the only place a hash is calculated repeatedly) isn't static, but there existed one inclstance per user, you wouldn't have to calculate the hash on every `Handle` call, but just once at the constructor.

**Comment by Azer0s** [comment]
Hmm...wait...yes. That is actually correct.

**Comment by Mitiko** [comment]
TODO:
- [ ] Make `NodeCommunicationClient` non-static
- [ ] Hash passwords at initialization of `NodeCommunicationClient`

**Comment by Azer0s** [comment]
@Mitiko Added salting to MD5. `NodeCommunicationClient` stays static for now (until we have our message queue).
